'use server';

/**
 * @fileOverview This file implements a Genkit flow that analyzes sales data to identify high-profit dishes and recommends potential price increases.
 *
 * - analyzeSalesDataForPricing - Analyzes sales data and suggests price increases for high-profit dishes.
 * - AnalyzeSalesDataForPricingInput - The input type for the analyzeSalesDataForPricing function.
 * - AnalyzeSalesDataForPricingOutput - The return type for the analyzeSalesDataForPricing function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SalesDataSchema = z.object({
  dishName: z.string().describe('The name of the dish.'),
  salesQuantity: z.number().describe('The quantity of the dish sold.'),
  revenue: z.number().describe('The total revenue generated by the dish.'),
  costOfGoodsSold: z.number().describe('The cost of goods sold for the dish.'),
});

const AnalyzeSalesDataForPricingInputSchema = z.object({
  salesData: z.array(SalesDataSchema).describe('An array of sales data for different dishes.'),
});
export type AnalyzeSalesDataForPricingInput = z.infer<
  typeof AnalyzeSalesDataForPricingInputSchema
>;

const PriceIncreaseRecommendationSchema = z.object({
  dishName: z.string().describe('The name of the dish recommended for a price increase.'),
  currentPrice: z.number().describe('The current price of the dish.'),
  suggestedNewPrice: z.number().describe('The suggested new price for the dish.'),
  reason: z.string().describe('The reasoning behind the price increase recommendation.'),
});

const AnalyzeSalesDataForPricingOutputSchema = z.object({
  recommendations: z
    .array(PriceIncreaseRecommendationSchema)
    .describe('An array of price increase recommendations.'),
});
export type AnalyzeSalesDataForPricingOutput = z.infer<
  typeof AnalyzeSalesDataForPricingOutputSchema
>;

export async function analyzeSalesDataForPricing(
  input: AnalyzeSalesDataForPricingInput
): Promise<AnalyzeSalesDataForPricingOutput> {
  return analyzeSalesDataForPricingFlow(input);
}

const analyzeSalesDataPrompt = ai.definePrompt({
  name: 'analyzeSalesDataPrompt',
  input: {schema: AnalyzeSalesDataForPricingInputSchema},
  output: {schema: AnalyzeSalesDataForPricingOutputSchema},
  prompt: `You are a pricing strategist for a restaurant. Analyze the following sales data to identify dishes with high profitability that could benefit from a slight price increase.  Provide a recommendation for each dish that meets this criteria.

Sales Data:

{{#each salesData}}
Dish Name: {{this.dishName}}
Sales Quantity: {{this.salesQuantity}}
Revenue: {{this.revenue}}
Cost of Goods Sold: {{this.costOfGoodsSold}}

{{/each}}

Based on this data, identify dishes that have a high sales quantity and a significant profit margin (Revenue - Cost of Goods Sold). For these dishes, recommend a small price increase (e.g., 5-10%) that could further improve profitability. Explain your reasoning for each recommendation. Output your answer as JSON.

Consider these safety settings when generating the response:
{
  "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
  "threshold": "BLOCK_ONLY_HIGH",
},
{
  "category": "HARM_CATEGORY_HARASSMENT",
  "threshold": "BLOCK_MEDIUM_AND_ABOVE",
},
{
  "category": "HARM_CATEGORY_HATE_SPEECH",
  "threshold": "BLOCK_ONLY_HIGH",
},
{
  "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
  "threshold": "BLOCK_LOW_AND_ABOVE",
}
`, // Added closing curly brace
})

const analyzeSalesDataForPricingFlow = ai.defineFlow(
  {
    name: 'analyzeSalesDataForPricingFlow',
    inputSchema: AnalyzeSalesDataForPricingInputSchema,
    outputSchema: AnalyzeSalesDataForPricingOutputSchema,
  },
  async input => {
    const {output} = await analyzeSalesDataPrompt(input);
    return output!;
  }
);
